### ISSUE TITLE
bootstrap doc outdated?

### ISSUE THREAD

**Issue by Luux** [Sage-Bionetworks/BridgePF#1723]
I'm currently trying to setup the server, but the boostrap doc seems a bit outdated.

Trying to setup the MySqlAuth gives the following error: "Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON Accounts (`studyId` ASC, `externalId` ASC),   INDEX `Accounts-StudyId-Index` ' at line 33"

Additionally, the play framework doesn't support the mentioned activator anymore: https://groups.google.com/forum/#!topic/play-framework/NeMD04W6bN4

EDIT: Ah okay, the Windows bootstrap says that I need Play 2.2.

**Comment by DwayneJengSage** [comment]
Bridge has been migrated from Play Framework to Spring Boot. The new repo and bootstrap docs are available at https://github.com/Sage-Bionetworks/BridgeServer2/wiki/bootstrap
